export enum EventTypes {
  unknown = 0,
  bannerRequest = 1,
  consentGranted = 2,
  consentNotGranted = 3,
  bannerIgnored = 4,
  learnMore = 5,
  emailShared = 6,
  emailEntered = 7,
  emailValidated = 8,
  openPassSso = 9,
  openPassFacebook = 10,
  openPassGoogle = 11,
  newIfa = 12,
  reuseIfa = 13,
  optOut = 14,
  optIn = 15,
  bannerOpened = 16,
}
