export enum EventTypes {
  unknown,
  bannerRequest,
  consentGranted,
  consentNotGranted,
  bannerIgnored,
  learnMore,
  emailShared,
  emailEntered = 7,
  emailValidated = 8,
  openPassSso = 9,
  openPassFacebook = 10,
  openPassGoogle = 11,
  newIfa = 12,
  reuseIfa = 13,
  optOut = 14,
  optIn = 15,
}
